from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AgentState(BaseModel):
    """
    Tracks the lifecycle and metrics of the current agent execution turn.
    """
    current_query: str = Field(..., description="The query being executed in this turn.")
    tools_used: List[str] = Field(default_factory=list, description="List of tools utilized in this execution.")
    tool_results: List[Dict[str, Any]] = Field(default_factory=list, description="Raw database outputs captured from executed tools.")
    iteration_count: int = Field(0, description="Steps taken in the while loop.")
    final_answer: Optional[str] = Field(None, description="The final conversational response generated by Gemini.")
    errors: List[str] = Field(default_factory=list, description="Logs of any encountered execution failures.")
