from pydantic import BaseModel, Field
from typing import List, Optional, Any

# General Chat Endpoints
class ChatRequest(BaseModel):
    message: str = Field(..., description="The user's natural language request.")
    session_id: Optional[str] = Field("default_session", description="Unique conversation session identifier.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The final answer generated by the agent.")
    tools_used: List[str] = Field(default_factory=list, description="List of tool names called during execution.")
    agent_iterations: int = Field(..., description="Total iterations/steps taken by the agent loop.")
    session_id: str = Field(..., description="The session ID representing the current memory context.")

# Tool: Weather Endpoint Schemas
class WeatherRequest(BaseModel):
    location: str = Field(..., description="The city or location name to query weather for.")

class WeatherResponse(BaseModel):
    location: str
    temperature: Optional[float] = None
    temperature_unit: Optional[str] = None
    condition: Optional[str] = None
    humidity: Optional[int] = None
    error: Optional[str] = None

# Tool: Time Endpoint Schemas
class TimeRequest(BaseModel):
    location: str = Field(..., description="The city or location name to query local time for.")

class TimeResponse(BaseModel):
    location: str
    timezone: Optional[str] = None
    current_time: Optional[str] = None
    error: Optional[str] = None

# Tool: Calculator Endpoint Schemas
class CalculatorRequest(BaseModel):
    expression: str = Field(..., description="The math expression to safely evaluate.")

class CalculatorResponse(BaseModel):
    expression: str
    result: Optional[Any] = None
    error: Optional[str] = None

# Tool: Location Endpoint Schemas
class LocationRequest(BaseModel):
    location: str = Field(..., description="The place or landmark name to query information for.")

class LocationResponse(BaseModel):
    place: str
    city: Optional[str] = None
    country: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    error: Optional[str] = None
